Dima tereschenko
Rassudov/TD-unity pull request #5
Opened 2017-11-26 03:46 UTC by Dima12101

Имеется:
-Дизайн
-Управление по размещению туреллей на платформах и её визуализация
-Управление камерой (зум и движение)
-Визуализация состояния здоровья врагов и их смертей
-Визуализация состояния денег, их траты и заработка
-Визуализация состояния фрагов и упущенных врагов
-Визуализация стрельбы
-Озвучка стрельбы, смерти, траты денег, заработка денег, а также упущенных врагов
-Фоновая музыка
-Наличие пилюль (временная прибавка скорости врагам)

2017-11-26 10:17 UTC, ghost requested changes
Проделана огромная работа, молодец! Звуки хороши, картинка радует глаз. Есть несколько мелких багов, которые, в принципе, устранимы.
1) Деньги могут уходить в минус
2) Игрок может приблизить камеру в структуры (и увидеть лишние ноды в подполье)
3) Хотелось бы увидеть хедеры. На некоторых объектах довольно много полей, хочется визуального разделения
4) Враги иногда некорректно ускоряются на пилюлях и застряют друг в друге

Баги, которые будут в приоритете к исправлению после слияния:
1) По непонятным причинам испаряются счетчики фрагов и пропущенных врагов
2) Просаживается фпс - слишком много объектов на сцене. Что делать с этим мне пока не совсем ясно, но делать надо.

2017-11-26 13:50 UTC, dimamelnik22 requested changes
Режет глаз загруженность функции SpawnBlood(). Неявное управление камерой (так и не понял как ей управлять пока все не закрыл и не пришел сюда читать код)
Ну а в целом остальное неплохо прям как твой скилл в теннисе. Ждем дальнейших продвижений.

2017-11-27 21:45 UTC, EvgenyOleshkevich requested changes
курсор вылетает за пределы карты и теряется там.

2017-11-28 02:33 UTC, Dima12101 commented
Результаты фикса:
-Управление платформами по размещению турелей работает корректно
-Невозможно больше уйти в минус по деньгам
-Счётчики фрагов и пропущенных врагов работают корректно
-Ограничение приближения камеры
-Отдаление камеры работает гладко (без дерганий). Отдаление происходит по принципу возвращения в начальную точку
-Камера теперь корректно двигается по полусфере (Принцип полусферы: 1. В начальной позиции камеру нельзя двигать в стороны. 2. Чем сильнее идёт приближение, тем больше радиус, по которому можно двигаться в стороны)
-Спаун крови был изменён: теперь это осуществляется за счёт частиц (fps значительно вырос)
-Немного было отредактировано визуализация стрельбы

2017-11-28 09:50 UTC, dimamelnik22 requested changes
Счетчик фрагов и пропущенных врагов перестал работать совсем, а вместе с ними и начисление денег. И правда после ускорения некоторые враги пролетают дальше и наслаиваются - надо исправлять. Кровь появляется только в одной полусфере, направленной постоянно вправо, и без учета скорости самого тела до взрыва.
Камера красиво и плавно летает, но управление остается неестественным...

2017-11-28 19:21 UTC, Dima12101 commented
Результаты последних двух коммитов:
1. Возвращено всё то, что было случайно удалено при правке кода 
2. Очередной фикс камеры. Дёрганье максимально устранено
3. Кровь спаунится теперь в правильном значение rotation
4. Установлен более корректный интервал спауна волн, дабы избежать бага со слиянием

2017-11-28 20:02 UTC, dimamelnik22 approved these changes
ну ты понел

2017-11-28 23:47 UTC, Dima12101 commented
-Подкорректирована визуализация здоровья врагов
-Изменён принцип стрельбы туреллей. Теперь для них в приоритете добить врага.
-Добавлен вид от первого лица для Турелей (для фана)
Управление:
--При зажатии клавиши Tab, камера располагается у первой найденной турели
--Не отжимая там с помощью стрелок Вправо(RightArrow) и Влево(LeftArrow) можно переключаться между турелями.
*Примечание: после отпуска клавиши Tab, возвращаетесь в то место, где нажимали

2017-11-29 09:46 UTC, Spiryacova approved these changes

2017-11-29 15:45 UTC, ghost approved these changes

2017-11-29 15:50 UTC, EvgenyOleshkevich approved these changes

2017-11-29 18:08 UTC, Godis715 approved these changes
Надо исправить баг с ускорителем - при больших значениях радиуса, ускоритель каждый апдейт воздействует на скорость эними, увеличивая ее в два раза -> enemy со скоростью света улетает за пределы карты

2017-11-29 18:40 UTC, merged