Evgeny map
Rassudov/TD-unity pull request #6
Opened 2017-11-26 13:42 UTC by EvgenyOleshkevich

1. создание карты.
2. боты.
3. 4 вида пушек ( турель, лазер, ракеты, башня заморозки) .
4. стрельба без эффекта.
5. замедление ботов.
6.  смерть ботов.
7. изменение цвета ботов при уменьшении здоровья или скорости.

2017-11-26 17:28 UTC, ghost requested changes
Интересная работа с заморозкой, молодец!
Много недопиленных вещей и хвостов заброшенных реализаций. Из-за этого много ошибок во время выполнения. В частности NullRefrenceException и переменные, которые никогда не используются. Зачисти скрипты. Заявленный функционал работает более-менее корректно, так что больше претензий нет.

2017-11-27 22:29 UTC, Dima12101 requested changes
Вариации видов турелей идёт в плюс. Но множество всплывающих ошибок не есть хорошо. Также надо поправить, чтобы объекты на сцену были добавлены от префаба. А то префаб имеет один вид, а объект на сцене уже всячески отредакчен. В дальнейшем приведёт к ошибкам. Надо поправить.

2017-11-28 09:28 UTC, dimamelnik22 requested changes
Страдает система наведения на цель (резкие скачки и повороты). По поводу замедления: хорошая идея но реализация не совсем ясна. Некоторые враги замораживаются уже после выхода из зоны действия, а другие не замораживаются, попав в радиус действия во время заморозки. Ну и модель замораживателя надо сделать красивенькую.

2017-12-03 16:23 UTC, dimamelnik22 commented
может наконец пора ОСТАНОВИТЬСЯ?

2017-12-05 17:33 UTC, merged