first pull request
Rassudov/TD-unity pull request #7
Opened 2017-11-26 22:10 UTC by dimamelnik22

ingame physics and mechanics (not UI)

2017-11-26 23:11 UTC, ghost requested changes
Плюс в карму за каноничную систему целеуказания и управление зумом камеры. В коде не хватает комментариев. На камер нужны ограничители на вылет. Нужно подумать как без особого ущерба для графики аккуратно убрать пули что бы добиться маскимального быстродействия. В целом хорошая стабильная версия, мне нравится).
З.Ы. Добавь два срипта в папочку, а то что как не родные?)

2017-11-27 18:18 UTC, Dima12101 commented
Всё, что было добавлено, работает без багов. Границы полёта камеры установить не помешало бы. Зачем кому-то видеть что там. Ну и дизайн оставляет желать лучшего. У меня всё)

2017-11-27 18:20 UTC, Dima12101 requested changes
Всё, что было добавлено, работает без багов. Границы полёта камеры установить не помешало бы. Зачем кому-то видеть что там. Ну и дизайн оставляет желать лучшего. У меня всё)

2017-11-27 18:52 UTC, Dima12101 approved these changes

2017-11-27 20:03 UTC, ghost approved these changes

2017-11-28 21:35 UTC, Spiryacova approved these changes

2017-11-29 18:31 UTC, EvgenyOleshkevich approved these changes
напиши 2 комментария в Node на 32 строке и в BuildManager к последней функции.

2017-11-29 18:50 UTC, EvgenyOleshkevich requested changes
напиши комментарии

2017-11-29 19:12 UTC, EvgenyOleshkevich approved these changes

2017-11-29 19:49 UTC, Godis715 approved these changes
Выглядит весьма кошерно, все (по крайней мере, что я видел), работает стройно и без лагов

P.s.  навигация на тачпаде - это просто убийство
либо добавь управление стрелочками, либо подари мне мышку

2017-11-29 21:03 UTC, merged